
spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: utf-8
#####druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: lizhihai
      url: jdbc:mysql://120.79.195.32:3306/miaosha?useTimezone=true&serverTimezone=CST&useUncoide=true&characterEncoding=utf-8
      filters: stat
      max-wait: 60000
      max-active: 1000
      initial-size: 10
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
####rabbitmq
  rabbitmq:
    password: guest
    username: guest
    host: 120.79.195.32
    port: 5672
    virtual-host: /
    template:
      retry:
        enabled: true
        max-attempts: 3
        multiplier: 1
        initial-interval: "2s"
        max-interval: 10000ms
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true




#mybatis
mybatis:
  type-aliases-package: com.lizhihai.miaosha.vo.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#redis
redis:
  port: 6379
  password: lizhihai
  host: 120.79.195.32
  timeout: 3
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 5

#tomcat
server:
  port: 80
